# Generated by Django 4.2.7 on 2024-11-01 03:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_V2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese_score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=100)])),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='grade.student_v2')),
            ],
        ),
    ]
