# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1te5q7VEV51yFhrQhxQrqJP6NmSgmkMnD
"""

import sys;


# hello world
print('hello world for Jarron')
# print hellowrld with variable
def hello(name, id):
    print('hello world in function')
    print('name is :', name)
    print('id is :', id)
def showpythonversion():
    print('python version is :', sys.version)
# call hello function
hello(name = '吳柏慶', id = 1100560)
showpythonversion()

