# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R2JuWyZdw5u3oQKeGJWqznIYz33gBoIO
"""

import sys;

print('hello world for Jarron')

def hello(name, id):
    print('hello world in function')
    print('name:', name)
    print('id:', id)

def showpythonversion():
    print('python version is :', sys.version)

hello(name = '許謹麟', id = 1110557)

showpythonversion()