# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11FtodMVk5blM2YRtFvV8xcBeKQskcSno
"""

import sys;

# hello world

print('hello world for Jarron')



# print hellowrld with variable
def hello(Name,ID):
    print('hello world in function')
    print('Name is:',Name)
    print('ID is:',ID)


def showpythonversion():
    print('python version is :', sys.version)

# call hello function
hello(Name = '陳俊瑋',ID = 1110672)

showpythonversion()



"""### My first Colab Program"""