# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PQfJMUUJTv_Eja-jDviP_y-QnjUff2RK
"""

import sys;

# hello world

print('hello world for Jarron')


# print hellowrld with variable
def hello(name,id):
    print('hello world in function')
    print('name is:',name)
    print('id is:',id)

def showpythonversion():
    print('python version is :', sys.version)


name='宋柏毅'
id=1110506
# call hello function
hello(name,id)

showpythonversion()