# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xD_FKrzFilxUr_n1JSzIBChINNlTOq12
"""

import sys;

# hello world
name='李彥承'
id=11105010
print('hello world for Jarron')


# print hellowrld with variable
def hello(name,id):
    print('hello world in function')
    print('name is:',name)
    print('id is:',id)

def showpythonversion():
    print('python version is :', sys.version)

# call hello function
hello(name,id)

showpythonversion()