# Generated by Django 5.1.2 on 2024-10-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("ST_ID", models.CharField(max_length=255)),
            ],
        ),
    ]
