# Generated by Django 5.1.3 on 2024-11-17 18:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_V2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('student_ID', models.CharField(default='ST_0000', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese_score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=100)])),
                ('english_score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=100)])),
                ('math_score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=100)])),
                ('physics_score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=100)])),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='grade.student_v2')),
            ],
        ),
    ]
