# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xD_FKrzFilxUr_n1JSzIBChINNlTOq12
"""

grade_list = [['John', 72, 88, 88, 84, 0, 0, 0],
              ['Eric', 88, 82, 77, 80, 0, 0, 0],
              ['Rick', 63, 49, 55, 68, 0, 0, 0],
              ['Mary', 72, 64, 82, 74, 0, 0, 0],
              ['Alice', 92, 79, 93, 89, 0, 0, 0],
              ['Match', 81, 72, 62, 70, 0, 0, 0],
              ['Sunny', 78, 77, 51, 72, 0, 0, 0]]

# 計算總分和平均分
for student in grade_list:
    total_score = sum(student[1:5])  # 前四科的總分
    avg_score = total_score / 4  # 平均分
    student[5] = total_score  # 更新總分
    student[6] = avg_score  # 更新平均分

# 按照總分排序，並計算名次
grade_list.sort(key=lambda x: x[5], reverse=True)  # 依據總分排序
for i in range(len(grade_list)):
    grade_list[i][7] = i + 1  # 更新名次

# 列印結果
print('姓名\t國文\t英文\t數學\t理化\t總分\t平均\t名次')
print('------------------------------------------------------------')

for student in grade_list:
    print(f'{student[0]}\t', end='')
    for score in student[1:]:
        print(f'{score}\t', end='')
    print()