# Generated by Django 4.2.7 on 2024-11-01 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_v2',
            name='student_ID',
            field=models.CharField(default='ST_0000', max_length=10),
        ),
    ]
