# Generated by Django 5.1.3 on 2024-11-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('st_id', models.CharField(default='ST_0000', max_length=255)),
            ],
        ),
    ]
